### ISSUE TITLE
How to specify CA certificate file in taxii cli?

### ISSUE THREAD

**Issue by vovanec** [eclecticiq/cabby#46] opened 2017-09-08 18:29 UTC
Hi guys

Let's say I'm using server certificate signed by certificate authority which is not widely known.
Is there any way to specify CA certificate when I'm using CLI to connect to the TAXII server? 

```
taxii-discovery --host taxii.example.net --port 443 --https --path services/discovery --username user --password ********

2017-09-08 11:26:39,100 ERROR: HTTPSConnectionPool(host='taxii.example.net', port=443): Max retries exceeded with url: /services/discovery (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)'),))
```

**Comment by traut** [comment] 2017-09-11 10:36
hey @vovanec. This functionality was missing. I made a pull request. Before I merge it, could you please checkout `add-ca-cert-in-cli` branch and verify that it works fine with your use case?

**Comment by vovanec** [comment] 2017-09-11 18:26
Hi @traut , I don't think it works. 

It looks like it's supposed to work only key_password parameter is passed(cabby.dispatcher.send_taxii_request). 

There are cases when I may need just to use CA certificate to verify the server, without client cert/key use.

Additional request - is this possible to add one more option, to skip server certificate check.

**Comment by aukjan** [comment] 2017-09-11 18:55
@vovanec, the option to skip validation is already present: '--verify'

**Comment by vovanec** [comment] 2017-09-11 18:58
Ah, I missed that. Thanks @aukjan

**Comment by rmeghnagi** [comment] 2018-04-17 17:52
Hi guys.

when i try to use the taxii-proxy command from cli, specifing to use https, the key and cert (--https --cert and --key options), this error appears:

error: unrecognized arguments: --https --cert --key

is there a way to specify these options with the taxii-proxy command?

**Comment by aukjan** [comment] 2018-04-18 05:12
Hi @rmeghnagi, 

This is not (yet) an option for the taxii proxy command, but I'll add this as a request.  Or you can add this to cabby if you need it.

**Comment by aukjan** [comment] 2018-04-18 11:00
let's continue the discussion in https://github.com/eclecticiq/cabby/issues/54 @rmeghnagi, which is the feature request issue.

**Comment by Mgajurel** [comment] 2018-09-17 08:48
Hi Guys,

I am trying to use the SSL authentication to setup a connection to a secured STIX source.

I can see a method named 'set_auth' as:
`set_auth(ca_cert=None, cert_file=None, key_file=None, key_password=None, username=None,
password=None, jwt_auth_url=None, verify_ssl=True)`

I had the understanding that we need a certificate file and a certificate key for SSL authentication but we have ca_cert, cert_file, key_file.
Why do we need a Certificate Authority certificate file (ca_cert) and another cert_file here?

I am really lost here, This is the first time I am practically using SSL authentication, although i have a simple idea of SSL authentication in theory.

Can anyone help me with this, is there some place where i can understand the entirety of it?

**Comment by andreasEIQ** [comment] 2018-09-28 14:18
Hey @Mgajurel - all of those arguments should be optional, just because you can provide them doesn't mean you have to. In your case, if you have a proper CA set up, you only need to pass in `ca_cert` and can ignore `key_file`, `cert_file` and so on.

**Comment by srtimsina** [comment] 2019-09-13 12:37
Hi @traut  and all,

I am facing the following error.

`(venv) ubuntu@ubuntu:~$ taxii-discovery --path https://localhost:9000/services/discovery-a --cert client.crt --key client.key -v`
2019-09-13 18:06:02,732 cabby.dispatcher INFO: Sending Discovery_Request to https://localhost:9000/services/discovery-a
2019-09-13 18:06:02,733 cabby.dispatcher DEBUG: Request:
<taxii_11:Discovery_Request xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="eefdb094-9f7d-4927-af80-459bead08a9d"/>

2019-09-13 18:06:02,739 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): localhost:9000
2019-09-13 18:06:02,756 cabby.cli.commons ERROR: HTTPSConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /services/discovery-a (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)'),))

**Comment by traut** [comment] 2019-09-13 13:12
@srtimsina do you have have webserver (nginx or similar) in front of your opentaxii that takes care of SSL? OpenTAXII does not provide SSL, it relies on a webserver for that

**Comment by srtimsina** [comment] 2019-09-14 10:04
@traut yes, we have Gunicorn as mentioned in the installation instruction [here](https://opentaxii.readthedocs.io/en/stable/running.html#production-mode).

**Comment by traut** [comment] 2019-09-14 10:39
@srtimsina that's not enough. Please re-read [SSL/TLS section](https://opentaxii.readthedocs.io/en/stable/running.html#using-ssl-tls) of the docs.

**Comment by srtimsina** [comment] 2019-09-14 15:38
@traut thank you, Do you mean Gunicorn is not enough and we need to setup Nginx or Apache web server in order to get it working?

**Comment by arcsector** [comment] 2019-09-14 19:27
@srtimsina yes; if you want protocol HTTPS then you need a web proxy. If you want to auth using a private/public keypair, you shouldnt need one.

**Comment by srtimsina** [comment] 2019-09-15 13:27
@arcsector , Well if i want to auth using a private/ public keypair, is the above setup okay. I has setup Gunicorn as mentioned in the [url] (https://opentaxii.readthedocs.io/en/stable/running.html#production-mode) Created the key pairs as discribed in the [url](https://tech-habit.info/posts/https-cert-based-auth-with-flask-and-gunicorn/)
Can you also verify the command below for taxii-discovery using the client cert and keys?
`(venv) ubuntu@ubuntu:~$ taxii-discovery --path https://localhost:9000/services/discovery-a --cert client.crt --key client.key -v`

**Comment by traut** [comment] 2019-09-15 13:30
@srtimsina if your command you are using `https://` schema that Gunicorn does not provide you. For that you need Nginx

**Comment by srtimsina** [comment] 2019-09-15 14:06
@traut, It's not supporting the `http://` either.

`(venv) ubuntu@ubuntu:~$ taxii-discovery --path http://localhost:9000/services/discovery-a --cert client.crt --key client.key
2019-09-15 19:50:35,242 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery-a
2019-09-15 19:50:35,260 ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))`

**Comment by traut** [comment] 2019-09-15 14:14
@srtimsina `Connection reset by peer` is a connection error that has nothing to do with the subject of this ticket - `How to specify CA certificate file in taxii cli`.

If you have trouble connecting to OpenTAXII ports, please check closed issues (there might be solutions there), and if you still don't have an answer - please open new issue

**Comment by srtimsina** [comment] 2019-09-23 14:23
Hi @traut @arcsector, Another ticket has been opened, [#144](https://github.com/eclecticiq/OpenTAXII/issues/144)

**Comment by erwin-eiq** [comment] 2021-09-03 13:54
The code from #47 matches the [requests documentation](https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) and therefore should fix the original issue. The comments in this issue don't disprove that point and most are off-topic entirely. Therefore, I am closing this issue.

@vovanec as the person who opened the issue, I'll allow you to re-open the ticket if you don't agree the originally described problem is fixed. If so, please provide a clear set of reproduction steps. Thanks for reporting the issue.

**Closed by erwin-eiq** 2021-09-03 13:54 UTC
